# OAuth2 AuthorizationService Clients
oauth2:
  clients:
    registeredClients[0]:
      clientId: first-app
      secret: '12345'
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
        - password
      authorities:
        - SupplyForm
      scopes:
        - read
      autoApprove: true
      registeredRedirectUris:
        - http://gemeente-akb:8081/login/gemeente
        - http://gemeente-akb:8080/login/gemeente
        - http://gemeente-akb/login/gemeente

datasource:
  users:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://db/gemeente-users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'gemeente-users'
    password: 'gemeente-users'
    hikari:
      idle-timeout: 10000

server:
  port: 8080
  servlet:
    context-path: /

content:
  resources:
    directory: /home/jelle/Environment/
  login:
    introduction: Welkom bij de Ichthus Gemeente website. Hier kunt u inloggen, of zichzelf aanmelden om toegang te krijgen tot de extra online diensten (o.a. AKB, foto's, etc).

logging:
  level:
    org:
      springframework: INFO
