# OAuth2 AuthorizationService Clients
oauth2:
  clients:
    registeredClients[0]:
      clientId: first-app
      clientDescription: 'First Sample App'
      secret: '12345'
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
        - password
      authorities:
        - SupplyForm
      scopes:
        - read
      autoApprove: true
      registeredRedirectUris:
        - http://gemeente-akb:8081/login/gemeente
        - http://gemeente-akb:8080/login/gemeente
        - http://gemeente-akb/login/gemeente

datasource:
  users:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://db/gemeente-users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'gemeente-users'
    password: 'gemeente-users'
    hikari:
      idle-timeout: 10000

server:
  port: 8080
  servlet:
    context-path: /

content:
  resources:
    # Make sure it ends with '/' (Available at '/external')
    directory: /etc/Environment/
  login:
    introduction: Welcome to the ... congregration website. You can logon here to get access the online services of our congregation (i.e. gift services, photo graphs, etc).
    not-registered: If you don't have an account yet, please register first (can be invitation only).
  register:
    introduction: Welcome to the ... congregration website. You have to register yourself before you can get access to the online services of our congregation (i.e. gift services, photo graphs, etc).
  title: Congregation Authorization Services
  footer: '&copy; Test congregation 2018'

logging:
  level:
    org:
      springframework: INFO
